pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
       
       }
        stage('push') {
            steps {
                sh 'curl -u admin:password -T /var/jenkins_home/workspace/arun/target/my-app-1.0-SNAPSHOT.jar "http://172.16.4.87:8081/artifactory/generic-local/my-app.jar"'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -DBranch=develop-1.0 -e -B sonar:sonar -Dsonar.host.url=http://172.16.4.87:9000 -Dsonar.login=5c07b656533d1b31555109e98f402e67f7953304 -Dsonar.scm.disabled=true -X
            }
        }
            }
    
}
